# For local use only!
version: '3.8'

services:
  front:
    build:
      context: ./front
    container_name: front
    ports:
      - "8000:8000"
    volumes:
      - ./front/front:/app/front
    environment:
      - ENVIRONMENT=dev

  aerospike:
    image: aerospike/aerospike-server:latest
    container_name: aerospike
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"