---
- name: Deploy front
  hosts: front
  any_errors_fatal: true
  vars:
    docker_image_name: front
    docker_container_name: front

  tasks:
    - name: Copy Dockerfile to target
      copy:
        src: ../front
        dest: /tmp

    - name: Build Docker image
      command: docker build -t {{ docker_image_name }} /tmp/front

    - name: Remove existing container if it exists
      docker_container:
        name: "{{ docker_container_name }}"
        state: absent
        force_kill: yes
        purge_networks: yes

    - name: Run Docker container
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image_name }}"
        state: started
        restart_policy: always
        ports:
          - "8000:8000"

    - name: Clean up Dockerfile from target
      file:
        path: /tmp/Dockerfile
        state: absent
